FROM nginx:1.25-alpine

ARG NGINX_FILE=./nginx/nginx.conf
RUN rm /etc/nginx/conf.d/default.conf
COPY ${NGINX_FILE} /etc/nginx/conf.d
# This allows access log redirection to stdout/stderr
RUN ln -sf /dev/stdout /var/log/nginx/access.log

EXPOSE 80 443
