"""add password reset token.

Revision ID: 19678bab3f2b
Revises: de229330a488
Create Date: 2024-05-16 22:00:53.082522

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "19678bab3f2b"
down_revision: str | None = "de229330a488"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "password_reset_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("query", sa.String(), nullable=False),
        sa.Column("created_timestamp", sa.DateTime(), nullable=False),
        sa.Column("expires_timestamp", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_password_reset_tokens_created_timestamp"),
        "password_reset_tokens",
        ["created_timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_password_reset_tokens_expires_timestamp"),
        "password_reset_tokens",
        ["expires_timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_password_reset_tokens_query"), "password_reset_tokens", ["query"], unique=True
    )
    op.create_index(
        op.f("ix_password_reset_tokens_user_id"), "password_reset_tokens", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_password_reset_tokens_user_id"), table_name="password_reset_tokens")
    op.drop_index(op.f("ix_password_reset_tokens_query"), table_name="password_reset_tokens")
    op.drop_index(
        op.f("ix_password_reset_tokens_expires_timestamp"), table_name="password_reset_tokens"
    )
    op.drop_index(
        op.f("ix_password_reset_tokens_created_timestamp"), table_name="password_reset_tokens"
    )
    op.drop_table("password_reset_tokens")
    # ### end Alembic commands ###
